### ISSUE TITLE
Make sure the time intervals are of the same magnitude in google football and vizdoom

### ISSUE THREAD

**Issue by MatthieuMoreau0** [HugoSenetaire/Google-Research-Football#8]
- In Vizdoom a step (after frame skipping) is equivalent to 116ms, so the max temporal offset of 32 steps is equivalent to 3.66 seconds

Make sure this is equivalent to what we have in google football other wise use frame skipping / reduce temporal offset to make up for it.

**Comment by HugoSenetaire** [comment]
In the article Kurach, K., Raichuk, A., Stańczyk, P., Zając, M., Bachem, O., Espeholt, L., ... & Gelly, S. (2020, April). Google research football: A novel reinforcement learning environment. In Proceedings of the AAAI Conference on Artificial Intelligence (Vol. 34, No. 04, pp. 4501-4510). :

"The length of the game is measured in terms of the
number of frames, and the default duration of a full game
is 3000 (10 frames per second for 5 minutes)."
